name: wireguard_flutter
description: Wireguard Flutter SDK
version: 0.1.0
homepage: https://flutterflux.com
repository: https://github.com/Caqil/wireguard_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.7'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  plugin_platform_interface: ^2.0.2
  process_run: ^0.14.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: billion.group.wireguard_flutter
        pluginClass: WireguardFlutterPlugin
      ios:
        pluginClass: WireguardFlutterPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: WireguardFlutterPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: WireguardFlutterPluginCApi
      linux:
        dartPluginClass: WireGuardFlutter
